language: cpp
compiler: gcc

matrix:
  include:
    - name: "GCC8"
      os: linux
      compiler: gcc-8
      env:
        - CCOMPILER=gcc-8
        - ASMCOMPILER=g++-8
        - CPPCOMPILER=g++-8
        - DYNAMICLINKER=g++-8
        - APPLINKER=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - nasm
            - libboost-dev
            - python3
            
    - name: "Clang6"
      os: linux
      compiler: clang-6.0
      env:
        - CCOMPILER=clang-6.0
        - ASMCOMPILER=clang++-6.0
        - CPPCOMPILER=clang++-6.0
        - DYNAMICLINKER=clang++-6.0
        - APPLINKER=clang++-6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
            - nasm
            - libboost-dev
            - python3

before_script:
  - $CPPCOMPILER --version
  - python3 --version
  - nasm -v

script:
  - python3 build.py rebuildall "all|-UtilTest"