language: cpp
compiler: gcc

matrix:
  include:
    - name: "GCC8"
      os: linux
      compiler: gcc-8
      env:
        - CCOMPILER=gcc-8
        - ASMCOMPILER=g++-8
        - CPPCOMPILER=g++-8
        - DYNAMICLINKER=g++-8
        - APPLINKER=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - nasm
            - python3
            - libx11-dev
            
    - name: "Clang6"
      os: linux
      compiler: clang-6.0
      env:
        - CCOMPILER=clang-6.0
        - ASMCOMPILER=clang++-6.0
        - CPPCOMPILER=clang++-6.0
        - DYNAMICLINKER=clang++-6.0
        - APPLINKER=clang++-6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-6.0
            - nasm
            - python3
            - libx11-dev

before_install:
  - mkdir tmp
  - cd tmp
  - mkdir include
  - wget -O boost_1_67_0.tar.bz2 https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2
  - tar xjf boost_1_67_0.tar.bz2
  - mv ./boost_1_67_0/boost ./include/
  - export CPP_DEPENDENCY_PATH=$(pwd)
  - cd ..

before_script:
  - echo $CPP_DEPENDENCY_PATH
  - $CPPCOMPILER --version
  - python3 --version
  - nasm -v

script:
  - python3 build.py rebuildall "all|-UtilTest"