dist: bionic
language: cpp

matrix:
  include:
    - name: "GCC7"
      os: linux
      compiler: gcc
      env:
        - CCOMPILER=gcc
        - ASMCOMPILER=g++
        - CPPCOMPILER=g++
        - DYNAMICLINKER=g++
        - APPLINKER=g++
        - BUILDMODULES="all"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - nasm
            - python3-pip
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libxi-dev
            
    - name: "GCC8"
      os: linux
      compiler: gcc
      env:
        - CCOMPILER=gcc-8
        - ASMCOMPILER=g++-8
        - CPPCOMPILER=g++-8
        - DYNAMICLINKER=g++-8
        - APPLINKER=g++-8
        - BUILDMODULES="all"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - nasm
            - python3-pip
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libxi-dev
            
    - name: "Clang7"
      os: linux
      compiler: clang
      env:
        - CCOMPILER=clang
        - ASMCOMPILER=clang++
        - CPPCOMPILER=clang++
        - DYNAMICLINKER=clang++
        - APPLINKER=clang++
        - BUILDMODULES="all"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-7-dev  # for LLVMgold.so
            - binutils-gold
            - binutils-dev
            - nasm
            - python3-pip
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libxi-dev
            
    - name: "Clang8"
      os: linux
      compiler: clang
      env:
        - CCOMPILER=clang-8
        - ASMCOMPILER=clang++-8
        - CPPCOMPILER=clang++-8
        - DYNAMICLINKER=clang++-8
        - APPLINKER=clang++-8
        - BUILDMODULES="all"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-8-dev  # for LLVMgold.so
            - binutils-gold
            - binutils-dev
            - nasm
            - python3-pip
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libxi-dev

before_install:
  - mkdir tmp
  - cd tmp
  - mkdir include
  - wget -O boost.tar.bz2 https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2
  - tar xjf boost.tar.bz2
  - mv ./boost_1_70_0/boost ./include/
  - export CPP_DEPENDENCY_PATH=$(pwd)
  - wget -O ispc.tar.gz https://sourceforge.net/projects/ispcmirror/files/v1.11.0/ispc-v1.11.0-linux.tar.gz/download
  - tar xzf ispc.tar.gz
  - export ISPCCOMPILER=$(find $(pwd) -type f -name ispc)
  - cd ..

before_script:
  - echo $CPP_DEPENDENCY_PATH
  - $CPPCOMPILER --version
  - $ISPCCOMPILER --version
  - python3 --version
  - python3 -m pip install pip
  - python3 -m pip install chardet
  - nasm -v

script:
  - python3 xzbuild.py rebuild $BUILDMODULES
  - python3 xzbuild.py rebuildall "SIMDTest" Release
  - ./x64/Release/SIMDTest
