language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - nasm
      - libboost-dev
      - python3

env:
  global:
    - CCOMPILER=gcc-7
    - ASMCOMPILER=g++-7
    - CPPCOMPILER=g++-7
    - DYNAMICLINKER=g++-7
    - APPLINKER=g++-7

before_script:
  - $CPPCOMPILER --version
  - python3 --version
  - nasm --version

script:
  - python3 build.py rebuildall all