dist: bionic
language: cpp

jobs:
  include:
    - name: "GCC7"
      os: linux
      compiler: gcc
      env:
        - CCOMPILER=gcc
        - ASMCOMPILER=g++
        - CPPCOMPILER=g++
        - DYNAMICLINKER=g++
        - APPLINKER=g++
        - BUILDMODULES="all,-BasicsTest,-NailangTest"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - nasm
            - unzip
            - python3-pip
            - libx11-dev
            - libx11-xcb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libxi-dev
            
    - name: "GCC8"
      os: linux
      compiler: gcc
      env:
        - CCOMPILER=gcc-8
        - ASMCOMPILER=g++-8
        - CPPCOMPILER=g++-8
        - DYNAMICLINKER=g++-8
        - APPLINKER=g++-8
        - BUILDMODULES="all,-BasicsTest,-NailangTest"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - nasm
            - unzip
            - python3-pip
            - libx11-dev
            - libx11-xcb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libxi-dev  

    - name: "GCC9"
      os: linux
      compiler: gcc
      env:
        - CCOMPILER=gcc-9
        - ASMCOMPILER=g++-9
        - CPPCOMPILER=g++-9
        - DYNAMICLINKER=g++-9
        - APPLINKER=g++-9
        - BUILDMODULES="all,-BasicsTest,-NailangTest"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - nasm
            - unzip
            - python3-pip
            - libx11-dev
            - libx11-xcb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libxi-dev
            
    - name: "Clang7"
      os: linux
      compiler: clang
      env:
        - CCOMPILER=clang
        - ASMCOMPILER=clang++
        - CPPCOMPILER=clang++
        - DYNAMICLINKER=clang++
        - APPLINKER=clang++
        - BUILDMODULES="all,-BasicsTest,-NailangTest"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - lld-7
            #- binutils-dev
            - nasm
            - unzip
            - python3-pip
            - libx11-dev
            - libx11-xcb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libxi-dev
            
    - name: "Clang8"
      os: linux
      compiler: clang
      env:
        - CCOMPILER=clang-8
        - ASMCOMPILER=clang++-8
        - CPPCOMPILER=clang++-8
        - DYNAMICLINKER=clang++-8
        - APPLINKER=clang++-8
        - BUILDMODULES="all,-BasicsTest,-NailangTest"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-8
            - lld-8
            #- binutils-dev
            - nasm
            - unzip
            - python3-pip
            - libx11-dev
            - libx11-xcb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libxi-dev

before_install:
  - mkdir tmp
  - cd tmp
  - mkdir include
  - mkdir src
  # - wget -O boost.tar.bz2 https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
  - wget -O boost.tar.bz2 https://iweb.dl.sourceforge.net/project/boost/boost/1.72.0/boost_1_72_0.tar.bz2
  - tar xjf boost.tar.bz2
  - mv ./boost_1_72_0/boost ./include/
  - wget -O gtest.zip https://github.com/google/googletest/archive/release-1.10.0.zip
  - unzip gtest.zip
  - cp -r ./googletest-release-1.10.0/googletest/include/gtest ./include/gtest
  - cp -r ./googletest-release-1.10.0/googlemock/include/gmock ./include/gmock
  - cd ./googletest-release-1.10.0/
  - mkdir build
  - cd build
  - cmake ..
  - make
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/lib
  - cd ../..
  - export CPP_DEPENDENCY_PATH=$(pwd)
  - wget -O ispc.tar.gz https://github.com/ispc/ispc/releases/download/v1.12.0/ispc-v1.12.0b-linux.tar.gz
  - tar xzf ispc.tar.gz
  - export ISPCCOMPILER=$(find $(pwd) -type f -name ispc)
  - cd ..

before_script:
  - echo $CPP_DEPENDENCY_PATH
  - $CPPCOMPILER --version
  - $ISPCCOMPILER --version
  - python3 --version
  - python3 -m pip install pip
  - python3 -m pip install chardet
  - nasm -v

script:
  - python3 xzbuild.py rebuild $BUILDMODULES /threads=x1.5
  - python3 xzbuild.py rebuildall "BasicsTest,NailangTest" Release /threads=x1.5
  - ./x64/Release/BasicsTest
  - ./x64/Release/NailangTest