#@XZBUILD
#@XZBUILD@description@charset operation utillities
#@XZBUILD@dependency@uchardet

BUILD_TYPE	:= dynamic

include $(PROJPATH)/Makebase.mk

NAME	= StringCharset

DEPLIBS		+= -luchardet


include $(PROJPATH)/MakeTargets.mk
